FROM openjdk:17.0.2-jdk-slim as build
MAINTAINER hyunho9877@gmail.com
COPY /build/libs/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/accounts-0.0.1-SNAPSHOT.jar"]