version: "3.8"

services:

  configserver:
    image: ruldarm00/config:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - ruldarm00
    environment:
      ENCRYPT_KEY: ddldddtkqslkxhddogkcrgnriklkurfqlstdsndqdkqnlrsdelrmfsdgdgkrdlwlsfhlnkdssjstmfqrrnalqfmsfwniksrPoruodgfrvdjtlkkhsldlnhghkavkceeiorkr

  eurekaserver:
    image: ruldarm00/eurekaserver:latest
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - ruldarm00
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: ruldarm00/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  loans:
    image: ruldarm00/loans:latest
    ports:
      - "8090:8090"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  cards:
    image: ruldarm00/cards:latest
    ports:
      - "9000:9000"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

networks:
  ruldarm00:
