version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "9411:9411"
    networks:
      - ruldarm00

  configserver:
    image: ruldarm00/config:latest
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8071:8071"
    networks:
      - ruldarm00
    environment:
      ENCRYPT_KEY: ddldddtkqslkxhddogkcrgnriklkurfqlstdsndqdkqnlrsdelrmfsdgdgkrdlwlsfhlnkdssjstmfqrrnalqfmsfwniksrPoruodgfrvdjtlkkhsldlnhghkavkceeiorkr
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: ruldarm00/eurekaserver:latest
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - ruldarm00
    depends_on:
      - configserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  accounts:
    image: ruldarm00/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  loans:
    image: ruldarm00/loans:latest
    ports:
      - "8090:8090"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  cards:
    image: ruldarm00/cards:latest
    ports:
      - "9000:9000"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gateway:
    image: ruldarm00/gateway:latest
    ports:
      - "8072:8072"
    networks:
      - ruldarm00
    depends_on:
      - configserver
      - eurekaserver
      - accounts
      - loans
      - cards
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  ruldarm00:
