deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 2

image:
  repository: ruldarm00/loans
  tag: latest

containerPort: 8090

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8090

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true