deploymentName: configserver-deployment
deploymentLabel: configserver

replicaCount: 1

image:
  repository: ruldarm00/config
  tag: latest

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

config_enabled: false
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false